name: Deploy App Container

on:
  push:
    branches: [ "main" ]
    paths:
      - "app/**"
      - ".github/workflows/deploy-app.yml"

jobs:
  deploy:
    name: Build & Push Docker Image â†’ ECR
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::144520190518:role/platform-infra-github-oidc-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag & Push Docker Image
        run: |
          IMAGE_TAG=$(date +%s)
          ECR_REPO="144520190518.dkr.ecr.us-east-1.amazonaws.com/dev-app"

          docker build -t dev-app:latest ./app
          docker tag dev-app:latest "$ECR_REPO:$IMAGE_TAG"
          docker tag dev-app:latest "$ECR_REPO:latest"

          docker push "$ECR_REPO:$IMAGE_TAG"
          docker push "$ECR_REPO:latest"

          echo "IMAGE_URI=$ECR_REPO:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update Terraform with new Image Tag
        run: |
          sed -i "s|ecr_image_uri = .*|ecr_image_uri = \"${IMAGE_URI}\"|g" envs/dev/main.tf

          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Actions"
          git add envs/dev/main.tf
          git commit -m "Deploy new image â†’ ${IMAGE_URI}" || echo "No changes"
          git push

      #####################################################
      # ðŸ”¥ TRIGGER TERRAFORM PLAN WORKFLOW (DISPATCH EVENT)
      #####################################################
      - name: Trigger terraform PLAN
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/africanvillain/platform-infra/dispatches \
            -d '{"event_type": "trigger-plan"}'

      #####################################################
      # ðŸ”¥ TRIGGER TERRAFORM APPLY WORKFLOW (DISPATCH EVENT)
      #####################################################
      - name: Trigger terraform APPLY
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/africanvillain/platform-infra/dispatches \
            -d "{\"event_type\": \"trigger-apply\"}"
