name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Pipeline
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ECR_REPO: ${{ secrets.ECR_REPO }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


          
      ########################################
      # DOCKER BUILD & PUSH TO ECR
      ########################################
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        working-directory: app
        run: |
          docker build -t app:latest .

      - name: Tag Docker image
        run: |
          docker tag app:latest $ECR_REPO:latest

      - name: Push Docker image
        run: |
          docker push $ECR_REPO:latest

      ########################################
      # TERRAFORM PIPELINE
      ########################################
      - name: Clean Terraform cache
        working-directory: envs/dev
        run: |
          rm -rf .terraform
          rm -f .terraform.lock.hcl

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        working-directory: envs/dev
        run: terraform init

      - name: Terraform Validate
        working-directory: envs/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: envs/dev
        run: terraform plan

      - name: Terraform Apply
        working-directory: envs/dev
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve


        